/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author LUID1.7
 */
public class Gênio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gênio.class.getName());
    
    /**
     * Creates new form Gênio
     */
    public Gênio() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBalaoDialogo = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        numeroSpinner = new javax.swing.JSpinner();
        lblGenioPng = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBalaoDialogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBalaoDialogo.setForeground(new java.awt.Color(0, 0, 0));
        lblBalaoDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalaoDialogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\GitHub\\prg03luidemanuelsantosdosanjos\\prg03luidemanuelsantosdosanjos\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\b2.png")); // NOI18N
        lblBalaoDialogo.setText("<html>Vou pensar  em um valor<br> entre 1 a 5. <br>Tente adivinhar</html>");
        lblBalaoDialogo.setToolTipText("");
        lblBalaoDialogo.setAutoscrolls(true);
        lblBalaoDialogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBalaoDialogo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblBalaoDialogo.setIconTextGap(-350);
        lblBalaoDialogo.setInheritsPopupMenu(false);
        lblBalaoDialogo.setVerifyInputWhenFocusTarget(false);

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPalpite.setText("PALPITE");
        btnPalpite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);

        numeroSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        lblGenioPng.setIcon(new javax.swing.ImageIcon("C:\\Users\\LUID1.7\\Documents\\GitHub\\prg03luidemanuelsantosdosanjos\\prg03luidemanuelsantosdosanjos\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\Genio pensativo (1).png")); // NOI18N
        lblGenioPng.setText("jLabel1");
        lblGenioPng.setIconTextGap(-100);

        jLabel1.setText("INFORME O NÚMERO AQUI");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addComponent(lblGenioPng, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(lblBalaoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblBalaoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGenioPng)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
        );

        lblBalaoDialogo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        int numeroEscolhido = Integer.parseInt(numeroSpinner.getValue().toString()); //Pegar valor do spinner e converter para int    
        int valorAleatorio = (int) (1 + Math.random() * 5); //Pegar um valor aleátorio entre 1 e 5
         if (numeroEscolhido == valorAleatorio){ //Verificar se o valor do palpite é igual ao valor aleatorio
               lblBalaoDialogo.setText("Acertou!!");
         }
         
         else{
              lblBalaoDialogo.setText("<html>Errou!! eu pensei no valor " + valorAleatorio); //Se valores for diferentes, imprime o valor certo
              
         }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gênio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBalaoDialogo;
    private javax.swing.JLabel lblGenioPng;
    private javax.swing.JSpinner numeroSpinner;
    // End of variables declaration//GEN-END:variables
} 


